version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: drf_blog_api_db
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: db
    networks:
      - default

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./source:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - default

networks:
  default:

volumes:
  postgres_data:
